apiVersion: batch/v1
kind: CronJob
metadata:
  name: unified-backup-job
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cloudsql-workload-sa
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: gcr.io/YOUR_PROJECT/unified-backup:latest
              command: ["python", "/backup.py"]
              env:
                - name: ENABLE_PG_BACKUP
                  value: "true"
                - name: ENABLE_BQ_BACKUP
                  value: "true"
                - name: PGUSER
                  value: "you@yourdomain.com"
                - name: PG_DATABASES
                  value: "db1,db2"
                - name: INSTANCE_CONNECTION_NAME
                  value: "your-project:region:instance"
                - name: GCS_BUCKET
                  value: "your-backup-bucket"
                - name: BQ_PROJECT
                  value: "your-bigquery-project"
                - name: BQ_DATASETS
                  value: "dataset1,dataset2"
              volumeMounts:
                - name: cloudsql
                  mountPath: /cloudsql
                - name: backup-disk
                  mountPath: /backup
            - name: cloudsql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:1.33.7
              command:
                - "/cloud_sql_proxy"
                - "-dir=/cloudsql"
                - "-instances=your-project:region:instance"
                - "-run_as_user=2"
                - "-run_as_group=2"
              volumeMounts:
                - name: cloudsql
                  mountPath: /cloudsql
          volumes:
            - name: cloudsql
              emptyDir: {}
            - name: backup-disk
              persistentVolumeClaim:
                claimName: pgsql-backup-pvc